### ISSUE TITLE
reflectivity_vertex.glsl compile error

### ISSUE THREAD

**Issue by pengbs** [abhishekBansal/nexrad-render#10]
when i compile reflectivity_vertex.glsl i got error "0:3: L0001: Expected identifier, found '['", but i dont know whats happen;
and i clone your code ,when i run its crash, logcat message:
`Error compiling shader:  0:2: L0001: Expected identifier, found '['
    
    --------- beginning of crash
2022-07-25 10:39:27.073 23747-23796/dev.abhishekbansal.nexrad E/AndroidRuntime: FATAL EXCEPTION: GLThread 33925
    Process: dev.abhishekbansal.nexrad, PID: 23747
    java.lang.RuntimeException: Error creating shader.
        at dev.abhishekbansal.nexrad.utils.Shader.compile(Shader.kt:45)
        at dev.abhishekbansal.nexrad.utils.Shader.<init>(Shader.kt:18)
        at dev.abhishekbansal.nexrad.layers.ReflectivityLayerHalfFloat$meshShader$2.invoke(ReflectivityLayerHalfFloat.kt:76)
        at dev.abhishekbansal.nexrad.layers.ReflectivityLayerHalfFloat$meshShader$2.invoke(ReflectivityLayerHalfFloat.kt:22)`

**Comment by pengbs** [comment]
i solved the problem，when i change  reflectivity_vertex.gls line 2  to 'uniform vec3 u_colorMap[86];' ,it works fine
